# PyTorch tensor walkthrough
- some simple examples of using PyTorch tensor objects

In [2]:
# import required library
import torch

In [3]:
# create a 2-dimensional 5x7 tensor with value 1 in every position
a = torch.ones(5, 7, dtype=torch.float)
a

tensor([[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]])

In [4]:
# define a non-symmetric matrix with zeros and 1's down the diagonal
b = torch.eye(5,7)
b

tensor([[1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0.]])

In [5]:
# define a square identity tensor
c = torch.eye(5,5)
c

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

# Examine tensor elements

In [6]:
b[0]

tensor([1., 0., 0., 0., 0., 0., 0.])

In [7]:
b[0,0]

tensor(1.)

In [8]:
b[2:]

tensor([[0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0.]])

In [35]:
# This one is okay too
b[2:,2:]


tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.]])

In [15]:
b[:2]

tensor([[1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0.]])

# Do operations on the tensors

In [17]:
# add two tensors with identical dimesions
a_plus_b = a + b
a_plus_b

tensor([[2., 1., 1., 1., 1., 1., 1.],
        [1., 2., 1., 1., 1., 1., 1.],
        [1., 1., 2., 1., 1., 1., 1.],
        [1., 1., 1., 2., 1., 1., 1.],
        [1., 1., 1., 1., 2., 1., 1.]])

In [16]:
# multiply two tensors - this cell will produce an error
a_mult_c = a@c
a_mult_c

RuntimeError: ignored

In [21]:
# define as 7 x 7 identity tensor
d = torch.eye(7,7)
d

tensor([[1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 1.]])

In [22]:
# multiply a tensor by the identity tensor
# (5 x 7) x (7 x 7) = (5, 7)
a_mult_d = a@d
a_mult_d

tensor([[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]])

In [23]:
# transpose a to get a 7x5 matrix
# transpose swap the (1,0) position to (0,1)
a_trans = torch.transpose(a,0,1)
a_trans

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [24]:
a_trans_mult_c = a_trans @ c
a_trans_mult_c

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [27]:
k = torch.rand(2,3)
k

tensor([[0.2867, 0.3341, 0.9063],
        [0.8328, 0.4341, 0.3288]])

In [30]:
# Args:
#    input (Tensor): the input tensor.
#    dim0 (int): the first dimension to be transposed
#    dim1 (int): the second dimension to be transposed
k_transpose = torch.transpose(k,0,1)
k_transpose

tensor([[0.2867, 0.8328],
        [0.3341, 0.4341],
        [0.9063, 0.3288]])

In [31]:
y = torch.rand(3,5)
y_transpose = torch.transpose(y,0,1)
y
y_transpose

tensor([[0.0667, 0.8654, 0.5013],
        [0.5284, 0.8657, 0.6256],
        [0.5109, 0.7786, 0.8958],
        [0.4998, 0.2655, 0.4263],
        [0.1802, 0.6168, 0.6323]])

In [32]:
y

tensor([[0.0667, 0.5284, 0.5109, 0.4998, 0.1802],
        [0.8654, 0.8657, 0.7786, 0.2655, 0.6168],
        [0.5013, 0.6256, 0.8958, 0.4263, 0.6323]])